### PR TITLE
Enable Cplex v12.8

### PR DESCRIPTION
**Pull request by g001234**
#148 Updated the definitions and parameters for Cplex v12.8. Has passed all tests. However, new features mentioned in this page (https://www.ibm.com/support/knowledgecenter/SSSA5P_12.8.0/ilog.odms.studio.help/CPLEX/ReleaseNotes/topics/releasenotes128/new.html) have not been addressed yet.

Please comment if there is any issue (except for adding the new callback features, which hopefully will be completed in the next week).

### CODE REVIEW

**Comment by mlubin** [comment]
Nice job! You should also run JuMP's 0.18's tests, since they stress parts of the API that may not be tested here. Is the old callback API still working?

**Comment by mlubin** [comment]
You should also update the list of supported versions in README.md.

**Comment by g001234** [comment]
Good point. I'll check the JuMP tests. I haven't tested callbacks either. From Cplex's release note, the current callbacks, i.e. legacy callbacks, don't seem to change. However, I'll check to make sure. 
Also, updated README.md.

**Comment by g001234** [comment]
Passed both CPLEX.jl and JuMP.jl tests, including the tests in .julia/v0.6/JuMP/test/callback.jl.

**Comment by mlubin** [comment]
Awesome

**Pull request merged**
