### PR TITLE
Fix for windows and v0.6

### PR DESCRIPTION
**Pull request by odow**
Passes tests on Windows Julia-0.5 and Julia-0.6

### CODE REVIEW

**Comment by tkelman** [comment]
why does the call to esc need to be version conditional at all?

**Comment by odow** [comment]
I just copied https://github.com/JuliaOpt/Xpress.jl/commit/6fe41930a5917b85c5c48309258f43829f77e55d

**Comment by odow** [comment]
Without the conditional (i.e. just the v0.6 branch) I get

```julia
julia> using CPLEX
INFO: Recompiling stale cache file C:\Users\odow003\.julia\lib\v0.5\CPLEX.ji for
 module CPLEX.
ERROR: LoadError: LoadError: syntax: ccall argument types must be a tuple; try "
(T,)"
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in macro expansion; at .\none:2 [inlined]
 in anonymous at .\<missing>:?
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:239
 in _start() at .\client.jl:318
while loading C:\Users\odow003\.julia\v0.5\CPLEX\src\cpx_env.jl, in expression s
tarting on line 1
while loading C:\Users\odow003\.julia\v0.5\CPLEX\src\CPLEX.jl, in expression sta
rting on line 85
ERROR: Failed to precompile CPLEX to C:\Users\odow003\.julia\lib\v0.5\CPLEX.ji.
 in compilecache(::String) at .\loading.jl:593
 in require(::Symbol) at .\loading.jl:393
```

**Comment by tkelman** [comment]
@mlubin do I remember you filing an issue about this? Wondering if it was https://github.com/JuliaLang/julia/pull/15850 or https://github.com/JuliaLang/julia/pull/18754 that caused the issue...

**Comment by mlubin** [comment]
I can't find any issue I filed about this.

**Comment by mlubin** [comment]
This might be the discussion you were remembering: https://discourse.julialang.org/t/macro-that-uses-ccall-in-julia-0-6-0/2639

**Pull request merged**
