### PR TITLE
fix Base warning

### LINKED ISSUE #223: Deprecated `Base.warn_once`
In https://github.com/JuliaOpt/CPLEX.jl/blob/master/src/CplexSolverInterface.jl#L198

`Base.warn_once` is deprecated, this causes an error in Julia > 0.7

### PR DESCRIPTION
**Pull request by matbesancon**
Fixes #223

### CODE REVIEW

**Comment by odow** [comment]
According to REQUIRE, we're still supporting Julia 0.6 so this needs a `Compat`.

Although I think we can remove and bump the minimum Julia version to 1.0 if you like.

**Comment by matbesancon** [comment]
REQUIRE bumped

**Comment by odow** [comment]
Presumably there are some `using Compat`s floating around as well.

**Comment by odow** [comment]
Thanks!

**Pull request merged**
