### PR TITLE
Implement solver independent parameters

### PR DESCRIPTION
**Pull request by odow**
@mlubin Copied from https://github.com/JuliaOpt/Gurobi.jl/pull/65

### CODE REVIEW

**Comment by mlubin** [comment]
These parameters should be set through ``setparameters!``, not mixed with the solver-specific parameters.

**Comment by odow** [comment]
Oh okay will fix.

**Comment by odow** [comment]
@mlubin how about now

**Comment by mlubin** [comment]
Looks good. You have permission to merge.

**Pull request merged**
