### PR TITLE
Enable CPLEX v12.7.1

### PR DESCRIPTION
**Pull request by blegat**
Nothing has changed in `cpxconst.h` except of course `CPX_VERSION` and `CPX_VERSION_MODIFICATION` and adding the parameters:
```
CPXPARAM_H = 1
CPXPARAM_Sifting_Simplex = 1158
CPXPUBLICPARAMS_H = 1
CPX_PARAM_SIFTSIM = 1158
```

### CODE REVIEW

**Comment by mlubin** [comment]
Did you account for the manual changes in ``full_defines_1271.jl``? What's the diff between ``full_defines_1271.jl`` and ``full_defines_127.jl``?

**Comment by blegat** [comment]
I did the manual changes needed (replace `Cint` by `Cchar` and remove `Cint` for floats). The diff is as follows
```
1c1
< # This list was obtained through AWK with Cplex 12.7 (and then pared down).
---
> # This list was obtained through AWK with Cplex 12.7.1 (and then pared down).
5c5
< const CPX_VERSION = convert(Cint,12070000)
---
> const CPX_VERSION = convert(Cint,12070100)
8c8
< const CPX_VERSION_MODIFICATION = convert(Cint,0)
---
> const CPX_VERSION_MODIFICATION = convert(Cint,1)
174,175d173
< #const CPX_BENDERS_ANNOTATION = convert(Cint,"cpxBendersPartition")
< const CPX_BENDERS_MASTERVALUE = convert(Cint,0)
405a404,405
> #const CPX_BENDERS_ANNOTATION = convert(Cint,"cpxBendersPartition")
> const CPX_BENDERS_MASTERVALUE = convert(Cint,0)
830a831
> const CPXPARAM_H = convert(Cint,1)
976a978
> const CPXPARAM_Sifting_Simplex = convert(Cint,1158)
1004a1007
> const CPXPUBLICPARAMS_H = convert(Cint,1)
1067a1071
> const CPX_PARAM_SIFTSIM = convert(Cint,1158)
```

**Comment by mlubin** [comment]
Looks good, I think the ``_H`` constants like ``CPXPARAM_H`` and ``CPXPUBLICPARAMS_H`` can be excluded since they're just header guards.

**Comment by mlubin** [comment]
There's also https://github.com/JuliaOpt/CPLEX.jl/issues/122 if you're feeling generous, but up to you.

**Pull request merged**
