### PR TITLE
Deprecation updates for Julia 0.5

### PR DESCRIPTION
**Pull request by odow**
This passes tests locally. 

Side note for interest. These deprecations caused a 2500% slow down in my algorithm run time because we are solving thousands of tiny LPs pertubing the RHS coefficients...

### CODE REVIEW

**Comment by mlubin** [comment]
Thanks @odow. Yes, deprecation warnings can cause significant slowdowns, more motivation to fix them ASAP.

**Comment by tkelman** [comment]
What happens if you try non-ascii values for these?

**Comment by mlubin** [comment]
@tkelman, quite possibly crashes, leads users to complain to IBM, and eventually they decide to support a CPLEX/Julia interface officially.

**Comment by tkelman** [comment]
That's a pretty user-hostile way to try to get IBM to care. Shouldn't that be easy enough to test for, and add a check to prevent crashes if it's an issue?

**Comment by odow** [comment]
Yeah good point. It's just an `isascii()` check but I don't have time to do right now.

**Comment by tkelman** [comment]
`Compat.String` is also not a concrete type on 0.4, which might make all the types slower

**Comment by tkelman** [comment]
Any update on testing this and/or fixing it with proper checks?

**Pull request merged**
