### PR TITLE
Fix Libdl moved to stdlib on v0.7

### LINKED ISSUE #159: Build failed for julia 0.7.0 on Ubuntu 17.10
```
julia> Pkg.add("CPLEX")
[ Info: Installing CPLEX v0.3.0
[ Info: Building CPLEX
┌ Warning: `is_apple` is deprecated, use `Sys.isapple` instead.
│   caller = top-level scope
└ @ Core :0
┌ Warning: `is_apple` is deprecated, use `Sys.isapple` instead.
│   caller = top-level scope at <missing>:24
└ @ Core <missing>:24
┌ Warning: `is_unix` is deprecated, use `Sys.isunix` instead.
│   caller = top-level scope at <missing>:26
└ @ Core <missing>:26
┌ Warning: `is_windows` is deprecated, use `Sys.iswindows` instead.
│   caller = top-level scope at <missing>:?
└ @ Core <missing>:-1
┌ Warning: Deprecated syntax `implicit assignment to global variable `found``.
│ Use `global found` instead.
└ @ nothing none:0
┌ Error: ------------------------------------------------------------
│ # Build failed for CPLEX
│   exception =
│    **LoadError: UndefVarError: Libdl not defined**
│    Stacktrace:
│     [1] top-level scope at ./<missing>:54
│     [2] include at ./boot.jl:292 [inlined]
│     [3] include_relative(::Module, ::String) at ./loading.jl:521
│     [4] include at ./sysimg.jl:26 [inlined]
│     [5] include(::String) at ./loading.jl:555
│     [6] top-level scope
│     [7] eval at ./boot.jl:295 [inlined]
│     [8] eval at ./sysimg.jl:71 [inlined]
│     [9] evalfile(::String, ::Array{String,1}) at ./loading.jl:550 (repeats 2 times)
│     [10] #2 at ./none:12 [inlined]
│     [11] cd(::getfield(, Symbol("##2#5")){String}, ::String) at ./file.jl:70
│     [12] (::getfield(, Symbol("##1#3")))(::IOStream) at ./none:11
│     [13] open(::getfield(, Symbol("##1#3")), ::String, ::String) at ./iostream.jl:310
│     [14] top-level scope
│     [15] eval at ./boot.jl:295 [inlined]
│     [16] eval(::Module, ::Expr) at ./sysimg.jl:71
│     [17] process_options(::Base.JLOptions) at ./client.jl:301
│     [18] _start() at ./client.jl:375
│    in expression starting at /home/aritra/.julia/v0.7/CPLEX/deps/build.jl:53
└ @ Main none:15
┌ Warning: ------------------------------------------------------------
│ # Build error summary
│ 
│ CPLEX had build errors.
│ 
│  - packages with build errors remain installed in /home/aritra/.julia/v0.7
│  - build the package(s) and all dependencies with `Pkg.build("CPLEX")`
│  - build a single package by running its `deps/build.jl` script
└ @ Base.Pkg.Entry entry.jl:650
[ Info: Package database updated
```
```
julia> versioninfo()
Julia Version 0.7.0-DEV.3413
Commit 5e2ff127f8 (2018-01-15 17:38 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
```

### PR DESCRIPTION
**Pull request by blegat**
Closes #159

### CODE REVIEW

**Comment by g001234** [comment]
Added those changes to my local branch, but got the following error while running `Pkg.test("CPLEX")`:
```
ERROR: LoadError: UndefVarError: Libdl not defined
Stacktrace:
 [1] top-level scope at /Users/chengguo/.julia/v0.6/CPLEX/src/CPLEX.jl:8
 [2] include at ./boot.jl:292 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:521
 [4] include(::Module, ::String) at ./sysimg.jl:26
 [5] top-level scope
 [6] eval at ./boot.jl:295 [inlined]
 [7] top-level scope at ./<missing>:2
in expression starting at /Users/chengguo/.julia/v0.6/CPLEX/src/CPLEX.jl:8
```
Then added `using Libdl` to CPLEX.jl, but the above problem persists.

The system is MacOS.

**Comment by blegat** [comment]
What does `julia -e 'println("$VERSION")'  print ?

**Comment by g001234** [comment]
0.7.0-DEV.3444

**Comment by blegat** [comment]
The 3 lines added in this PR need to also be added to CPLEX.jl

**Comment by blegat** [comment]
@g001234 What about now ?

**Pull request merged**
