### PR TITLE
Try to make CPLEX fail gracefully on SIGINT

### PR DESCRIPTION
**Pull request by joehuchette**
Want to try this out @sbebo? Seems to work for me.

### CODE REVIEW

**Comment by joehuchette** [comment]
ref #45

**Comment by sbebo** [comment]
Looks good.. but I still see segfaults. They are somewhat less frequent in the REPL. Outside of the REPL I get a segfault nearly (but not quite) all the time.
Might be an issue with my version of Julia. I'm testing with: 
```julia
Julia Version 0.3.10
Commit c8ceeef* (2015-06-24 13:54 UTC)
Platform Info:
System: Darwin (x86_64-apple-darwin14.3.0)
```

By the way, it might be worth discussing whether one would like ctrl+c to actually kill the whole thing  or just terminate the optimization (the `exit_on_sigint=0` hack should do that -- in theory) when running a Julia script from the command line (as in `julia test.jl`). 
For sure is what you want in the REPL; not 100% sure you want that outside of the REPL, but not a big deal anyway.

**Comment by joehuchette** [comment]
Hmm yeah, I'm also seeing the old behavior on v0.3. I've also reproduced a segfault twice in about 15 runs on v0.4.

**Comment by joehuchette** [comment]
To add to the mix, I'm now sometimes getting
```
...
    539   492    95870.8967     0    96735.0536     8281.5550    17830   91.44%
   1172  1026    28317.6552    58    96735.0536     9456.3217    44564   90.22%
   1827  1567    15980.2780    91    96735.0536     9985.4947    70648   89.68%
^C
signal (10): Bus error: 10
CPXEgeneric_unlock at /Users/huchette/Applications/ILOG/CPLEX_Studio126/cplex/bin/x86-64_osx/cplex (unknown line)
CPXLstoreNEThandle at /Users/huchette/Applications/ILOG/CPLEX_Studio126/cplex/bin/x86-64_osx/cplex (unknown line)
CPXEgeneric_unlock at /Users/huchette/Applications/ILOG/CPLEX_Studio126/cplex/bin/x86-64_osx/cplex (unknown line)
CPXEgeneric_unlock at /Users/huchette/Applications/ILOG/CPLEX_Studio126/cplex/bin/x86-64_osx/cplex (unknown line)
_pthread_body at /usr/lib/system/libsystem_pthread.dylib (unknown line)
_pthread_body at /usr/lib/system/libsystem_pthread.dylib (unknown line)
[1]    7521 bus error  /Applications/Julia-0.3.8.app/Contents/Resources/julia/bin/julia
```

**Comment by sbebo** [comment]
I think I've seen that too.

**Pull request closed without merging**
