### PR TITLE
fix multiple loadproblem! calls

### PR DESCRIPTION
**Pull request by blegat**
I first tried the `finalize_env` mechanism used in Gurobi.jl but it gave me segfault because it happened that the model that is thrown away gets gc'd second which cause it to be freed after the environment has already been freed by the new model that was gc'd first.

### CODE REVIEW

**Comment by mlubin** [comment]
It seems suspicious that we would need to manually implement a reference counter. Is there a simpler fix?

**Comment by blegat** [comment]
Since each problem has a reference to the environment we might just trust Julia's GC to detect when to delete `Env`

**Comment by mlubin** [comment]
@blegat, see discussion at https://github.com/JuliaLang/julia/issues/3067

**Comment by blegat** [comment]
@mlubin Thanks for the link.

So we know that when the Env finalizer is called, it is no longer referenced any where so the user will not create new models or use any models and the finalizer of all models have either already been called or are going to be called soon. Is see two solutions
* Have a counter in `Env` and a `Bool` saying whether the GC has already called finalized.
   * In the Env finalizer, if the counter is 0, free it otherwise, just set the `Bool` to `true`.
   * In the Model finalizer, free the model and ask the env to decrease the counter. If the counter goes to zero and the `Bool` is `true`, free the env.
* Have a list of models in `Env` and a `Bool` in `Model` to say whether the Model has already been freed
   * In the Env finalizer, for every problem in the list, free it then free the Env.
   * In the Model finalizer, free it then remove it from `Env`'s list.

Which one do you prefer ?

**Comment by mlubin** [comment]
I'm a bit confused here. Would the issue be resolved by the approach in [Gurobi.jl](https://github.com/JuliaOpt/Gurobi.jl#reusing-the-same-gurobi-environment-for-multiple-solves) where you can optionally provide an Env to the Model object, in which case the model's finalizer won't free the Env? We can tell people to do this if they need to call ``loadproblem!`` more than once.

**Comment by blegat** [comment]
Who is going to free the `Env` then ?

**Comment by mlubin** [comment]
The finalizer for the ``Env``, as it should.

**Comment by blegat** [comment]
But then what prevents `Env` to be finalized before the models ?
In gurobi, the `Env` does not call the finalizer, it is commented
```
# finalizer(env, free_env)  ## temporary disable: which tends to sometimes caused warnings
```

**Comment by mlubin** [comment]
Good question, I didn't know that was disabled. Ok, let's go ahead with the manual reference counting. Whichever approach you prefer.

**Comment by blegat** [comment]
I have implemented the first one :)

**Pull request merged**
